#!/usr/bin/env python
"""Capture schema fixtures from a real audiobookshelf server.

Generated by Claude (Anthropic's Claude Code) as a development tool for this
repository.

The schemas in this package were written from abs' source, not from its answers.
This records what a live server actually sends, so the test suite can hold the
schemas to it. Run it against a test instance and review what it wrote.

    ABS_URL=http://abs.local:13378 ABS_USERNAME=... ABS_PASSWORD=... \
        .venv/bin/python scripts/capture_fixtures.py

Nothing is written until every capture has been sanitised. Tokens, paths, host
names and user names are replaced; a payload still carrying something that looks
like a secret aborts the whole run. ABS_SOCKET_SECONDS=0 skips the socket,
ABS_KEEP_RAW=1 also writes the unsanitised captures, to see what was removed.

--verify decodes the fixtures already on disk and talks to no server, so it
needs no credentials. Either way the exit code is 0 only if every fixture the
package has a schema for could be read.
"""

import argparse
import asyncio
import json
import os
import re
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime
from importlib import import_module
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import aiohttp
import socketio

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures"
RAW = ROOT / "fixtures-raw"

# python puts this script's own directory on the path, not the repository
sys.path.insert(0, str(ROOT))

# how many entries of a list we keep, one is rarely enough to show a variant
KEEP = 2
# how long we listen for socket events, while you click around in abs' web ui
SOCKET_SECONDS = 60

PLACEHOLDER_URL = "https://abs.example.com"
PLACEHOLDER_PATH = "/audiobooks"

# these carry credentials
SECRET_KEYS = {
    "token",
    "accesstoken",
    "refreshtoken",
    "apikey",
    "password",
    "secret",
    "authorization",
    "cookie",
}
# these carry the server's filesystem layout
PATH_KEYS = {
    "path",
    "relpath",
    "fullpath",
    "metadatapath",
    "folderpath",
    "libraryfolder",
    "contenturl",
    "coverpath",
    "audiofilepath",
    "backuppath",
}
# these identify a person
NAME_KEYS = {"username": "listener", "email": "listener@example.com"}

# what must never survive sanitising, whatever key it hides under
SECRET_SHAPES = (re.compile(r"eyJ[\w-]{10,}"), re.compile(r"token=[^&\s\"]+"))

# an endpoint to capture: its fixture name, where to ask, and the schema the
# client decodes the answer with. A library endpoint also carries its query.
Account = tuple[str, str, str]
Endpoint = tuple[str, str, str, dict[str, Any]]

# account wide endpoints
ACCOUNT: list[Account] = [
    ("me", "/api/me", "user.User"),
    ("items_in_progress", "/api/me/items-in-progress", "calls_me.ItemsInProgressResponse"),
    ("listening_sessions", "/api/me/listening-sessions", "calls_me.MeListeningSessionsResponse"),
    ("playlists", "/api/playlists", "calls_playlists.AllPlaylistsResponse"),
    ("collections", "/api/collections", "calls_collections.AllCollectionsResponse"),
]

# per library, {} being the library's own endpoint
PAGED: dict[str, Any] = {"limit": KEEP, "page": 0}
MINIFIED: dict[str, Any] = PAGED | {"minified": 1}
LIBRARY: list[Endpoint] = [
    ("library", "{}", "library.Library", {}),
    (
        "library_with_filterdata",
        "{}",
        "calls_library.LibraryWithFilterDataResponse",
        {"include": "filterdata"},
    ),
    ("filterdata", "{}/filterdata", "library.LibraryFilterData", {}),
    ("personalized", "{}/personalized", "shelf.Shelf", {"limit": KEEP}),
    ("items", "{}/items", "calls_library.LibraryItemsMinifiedResponse", MINIFIED),
    ("series", "{}/series", "calls_library.LibrarySeriesMinifiedResponse", MINIFIED),
    ("collections", "{}/collections", "calls_library.LibraryCollectionsMinifiedResponse", MINIFIED),
    ("playlists", "{}/playlists", "calls_library.LibraryPlaylistsResponse", PAGED),
]
# what SocketClient decodes each event with, so the report covers them too
EVENT_MODELS: dict[str, str] = {
    "user_updated": "user.User",
    "user_item_progress_updated": "events_socket.UserItemProgressUpdatedEvent",
    "item_added": "library.LibraryItemExpanded",
    "item_updated": "library.LibraryItemExpanded",
    "item_removed": "events_socket.LibraryItemRemoved",
    "episode_added": "events_socket.PodcastEpisodeAdded",
    "episode_download_finished": "events_socket.PodcastEpisodeDownload",
    "library_added": "library.Library",
    "library_updated": "library.Library",
    "library_removed": "library.Library",
    "playlist_added": "playlist.PlaylistExpanded",
    "playlist_updated": "playlist.PlaylistExpanded",
    "playlist_removed": "playlist.PlaylistExpanded",
    "author_added": "author.Author",
    "author_updated": "author.AuthorExpanded",
    "author_removed": "events_socket.AuthorRemoved",
    "stream_open": "streams.Stream",
    "stream_progress": "streams.StreamProgress",
    "stream_reset": "events_socket.StreamReset",
    "stream_error": "events_socket.StreamError",
}

# only a book library answers these
BOOK_ONLY: list[Endpoint] = [
    ("authors", "{}/authors", "calls_library.LibraryAuthorsResponse", {}),
    ("narrators", "{}/narrators", "calls_library.LibraryNarratorsResponse", {}),
]


class SecretLeakError(Exception):
    """Raised when a capture still holds something secret shaped."""


def _normalise(key: str) -> str:
    return key.lower().replace("_", "").replace("-", "")


def sanitise(value: Any, *, server_url: str) -> Any:
    """Return a copy of an abs payload that is safe to commit."""
    if isinstance(value, dict):
        return {
            key: _sanitise_member(key, member, server_url=server_url)
            for key, member in value.items()
        }
    if isinstance(value, list):
        return [sanitise(member, server_url=server_url) for member in value]
    if isinstance(value, str):
        text = value.replace(server_url.rstrip("/"), PLACEHOLDER_URL)
        for shape in SECRET_SHAPES:
            text = shape.sub("removed", text)
        return text
    return value


def _sanitise_member(key: str, value: Any, *, server_url: str) -> Any:
    name = _normalise(key)
    if name in SECRET_KEYS:
        return None if value is None else f"{key}-removed"
    if name in NAME_KEYS and isinstance(value, str):
        return NAME_KEYS[name]
    if name in PATH_KEYS and isinstance(value, str):
        return f"{PLACEHOLDER_PATH}/{Path(value).name}"
    return sanitise(value, server_url=server_url)


def assert_clean(value: Any, *, where: str = "") -> None:
    """Refuse a payload which still looks like it carries a secret."""
    if isinstance(value, dict):
        for key, member in value.items():
            assert_clean(member, where=f"{where}.{key}")
    elif isinstance(value, list):
        for index, member in enumerate(value):
            assert_clean(member, where=f"{where}[{index}]")
    elif isinstance(value, str):
        for shape in SECRET_SHAPES:
            if shape.search(value):
                raise SecretLeakError(f"{where or 'payload'}: {value[:40]}")


def trim(value: Any) -> Any:
    """Keep a fixture small: a few entries of every list are enough."""
    if isinstance(value, dict):
        return {key: trim(member) for key, member in value.items()}
    if isinstance(value, list):
        return [trim(member) for member in value[:KEEP]]
    return value


@dataclass
class Capture:
    """One recorded answer or event."""

    name: str
    source: str
    model: str
    payload: Any


@dataclass
class Server:
    """A live abs, answering with raw json."""

    url: str
    session: aiohttp.ClientSession
    token: str = ""
    captures: list[Capture] = field(default_factory=list)

    async def login(self, username: str, password: str) -> None:
        """Log in and keep the access token for the calls that follow."""
        async with self.session.post(
            f"{self.url}/login",
            json={"username": username, "password": password},
            headers={"x-return-tokens": "true"},
            raise_for_status=True,
        ) as response:
            payload = await response.json()
        user = payload["user"]
        self.token = user.get("accessToken") or user["token"]
        self.record("login", "POST /login", "calls_login.LoginResponse", payload)

    async def capture(
        self, name: str, endpoint: str, model: str, params: dict[str, Any] | None = None
    ) -> Any:
        """Record what one endpoint answers, or nothing when abs says no."""
        async with self.session.get(
            f"{self.url}{endpoint}",
            params={key: str(value) for key, value in (params or {}).items()},
            headers={"Authorization": f"Bearer {self.token}"},
        ) as response:
            if response.status != 200 or response.content_type != "application/json":
                print(f"  skipped {endpoint} ({response.status} {response.content_type})")
                return None
            payload = await response.json()
        self.record(name, f"GET {endpoint}", model, payload)
        return payload

    def record(self, name: str, source: str, model: str, payload: Any) -> None:
        """Keep a capture, and say so."""
        print(f"  captured {name} from {source}")
        self.captures.append(Capture(name=name, source=source, model=model, payload=payload))


async def capture_rest(server: Server, username: str, password: str) -> None:
    """Walk the endpoints this package has schemas for."""
    print("rest:")
    await server.login(username, password)
    for name, endpoint, model in ACCOUNT:
        await server.capture(name, endpoint, model)

    libraries = await server.capture(
        "libraries", "/api/libraries", "calls_library.AllLibrariesResponse"
    )
    # one library of each kind is enough, and a second would overwrite its fixtures
    seen = set()
    for library in (libraries or {}).get("libraries", []):
        kind = library["mediaType"]
        if kind in seen:
            continue
        seen.add(kind)
        print(f"  library {library['name']} ({kind}):")
        await capture_library(server, library["id"], kind)


async def capture_library(server: Server, library_id: str, kind: str) -> None:
    """Everything that hangs off one library."""
    base = f"/api/libraries/{library_id}"
    items = None
    for name, endpoint, model, params in LIBRARY + (BOOK_ONLY if kind == "book" else []):
        payload = await server.capture(f"{name}_{kind}", endpoint.format(base), model, params)
        if name == "items":
            items = payload

    results = (items or {}).get("results") or []
    if not results:
        return
    item_id = results[0]["id"]
    item = await server.capture(
        f"item_expanded_{kind}",
        f"/api/items/{item_id}",
        f"library.LibraryItemExpanded{kind.capitalize()}",
        {"expanded": 1},
    )
    episodes = (item or {}).get("media", {}).get("episodes") or []
    if episodes:
        await server.capture(
            "podcast_episode",
            f"/api/podcasts/{item_id}/episode/{episodes[0]['id']}",
            "podcast.PodcastEpisode",
        )


async def capture_socket(server: Server, seconds: int) -> None:
    """Record whatever abs pushes while you use its web ui."""
    print(f"socket: listening for {seconds}s — change something in abs' web ui now")
    client = socketio.AsyncClient(reconnection=False)
    seen: dict[str, Any] = {}

    async def on_connect() -> None:
        await client.emit("auth", server.token)

    async def on_any(event: str, *args: Any) -> None:
        if event not in seen and args:
            seen[event] = args[0]
            print(f"  captured event {event}")

    client.on("connect", handler=on_connect)
    client.on("*", handler=on_any)

    await client.connect(url=server.url, socketio_path=f"{urlparse(server.url).path}/socket.io")
    await asyncio.sleep(seconds)
    await client.disconnect()

    for event, payload in seen.items():
        server.record(f"event_{event}", f"socket {event}", EVENT_MODELS.get(event, ""), payload)


def model_for(name: str, manifest: dict[str, Any]) -> str:
    """Name the schema a fixture should decode as. An event knows its own."""
    if name.startswith("event_"):
        return EVENT_MODELS.get(name.removeprefix("event_").removesuffix(".json"), "")
    entry = manifest.get(name)
    return str(entry["model"]) if entry else ""


def report() -> int:
    """Decode every fixture on disk, this run's and the ones an earlier run left."""
    print("decoding with the current schemas:")
    failures = 0
    manifest = read_manifest()["fixtures"]
    for path in sorted(FIXTURES.glob("*.json")):
        if path.name == "manifest.json":
            continue
        model_name = model_for(path.name, manifest)
        if not model_name:
            print(f"  ?     {path.stem} (no schema for it)")
            continue
        module_name, _, class_name = model_name.partition(".")
        model = getattr(import_module(f"aioaudiobookshelf.schema.{module_name}"), class_name)
        payload = json.loads(path.read_text())
        payloads = payload if isinstance(payload, list) else [payload]
        try:
            for member in payloads:
                model.from_payload(member)
        except Exception as err:  # noqa: BLE001
            failures += 1
            print(f"  FAILS {path.stem} as {class_name}: {type(err).__name__}: {err}")
        else:
            print(f"  ok    {path.stem}")
    return failures


def read_manifest() -> dict[str, Any]:
    """Load what earlier runs left behind, so their fixtures keep being checked."""
    path = FIXTURES / "manifest.json"
    if not path.exists():
        return {"fixtures": {}}
    loaded: dict[str, Any] = json.loads(path.read_text())
    return loaded


def write(captures: list[Capture], server_url: str, *, keep_raw: bool) -> None:
    """Sanitise, trim and write. No fixture lands on disk before every check passed."""
    if keep_raw:
        RAW.mkdir(parents=True, exist_ok=True)
        for capture in captures:
            (RAW / f"{capture.name}.json").write_text(json.dumps(capture.payload, indent=2) + "\n")
        print(f"  wrote the unsanitised captures to {RAW} — do not commit those")

    print("sanitising:")
    cleaned = []
    for capture in captures:
        payload = trim(sanitise(capture.payload, server_url=server_url))
        assert_clean(payload, where=capture.name)
        cleaned.append((capture, payload))
    print(f"  {len(cleaned)} captures are clean")

    FIXTURES.mkdir(parents=True, exist_ok=True)
    manifest = read_manifest()["fixtures"]
    for capture, payload in cleaned:
        (FIXTURES / f"{capture.name}.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n"
        )
        manifest[f"{capture.name}.json"] = {"source": capture.source, "model": capture.model}
    (FIXTURES / "manifest.json").write_text(
        json.dumps(
            {"captured": datetime.now(UTC).strftime("%Y-%m-%d"), "fixtures": manifest},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    print(f"  wrote {len(cleaned)} fixtures to {FIXTURES}")


async def main(*, verify_only: bool) -> int:
    """Capture, write, report. With verify_only, only report."""
    if verify_only:
        if not any(FIXTURES.glob("*.json")):
            print(f"no fixtures in {FIXTURES}, capture some first")
            return 2
        return 1 if report() else 0

    url = os.environ.get("ABS_URL", "").rstrip("/")
    username = os.environ.get("ABS_USERNAME", "")
    password = os.environ.get("ABS_PASSWORD", "")
    if not url or not username or not password:
        print("set ABS_URL, ABS_USERNAME and ABS_PASSWORD")
        return 2
    seconds = int(os.environ.get("ABS_SOCKET_SECONDS", str(SOCKET_SECONDS)))

    async with aiohttp.ClientSession() as session:
        server = Server(url=url, session=session)
        await capture_rest(server, username, password)
        if seconds:
            await capture_socket(server, seconds)
        # write first: a capture costs a minute of clicking, a report costs nothing
        write(server.captures, url, keep_raw=bool(os.environ.get("ABS_KEEP_RAW")))
        failures = report()
    return 1 if failures else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.partition("\n")[0])
    parser.add_argument(
        "--verify",
        action="store_true",
        help="only decode the fixtures already on disk, capture nothing",
    )
    sys.exit(asyncio.run(main(verify_only=parser.parse_args().verify)))
